// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyItem(arg1) {
  return window['go']['app']['App']['CopyItem'](arg1);
}

export function CopyRemoteImage(arg1, arg2) {
  return window['go']['app']['App']['CopyRemoteImage'](arg1, arg2);
}

export function CopyRemoteItem(arg1) {
  return window['go']['app']['App']['CopyRemoteItem'](arg1);
}

export function GetConfigPath() {
  return window['go']['app']['App']['GetConfigPath']();
}

export function GetHistory() {
  return window['go']['app']['App']['GetHistory']();
}

export function GetRemoteClipboards() {
  return window['go']['app']['App']['GetRemoteClipboards']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function NeedsPassphrase() {
  return window['go']['app']['App']['NeedsPassphrase']();
}

export function RemoteClipboardsEnabled() {
  return window['go']['app']['App']['RemoteClipboardsEnabled']();
}

export function SubmitPassphrase(arg1) {
  return window['go']['app']['App']['SubmitPassphrase'](arg1);
}
