// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clipboard} from '../models';
import {peersclipsync} from '../models';
import {theme} from '../models';

export function CopyItem(arg1:string):Promise<void>;

export function CopyRemoteImage(arg1:string):Promise<void>;

export function CopyRemoteItem(arg1:string):Promise<void>;

export function GetHistory():Promise<Array<clipboard.ClipboardEntry>>;

export function GetRemoteClipboards():Promise<Array<peersclipsync.PeerClipboard>>;

export function GetTheme():Promise<theme.ThemeColors>;

export function NeedsPassphrase():Promise<boolean>;

export function RemoteClipboardsEnabled():Promise<boolean>;

export function SubmitPassphrase(arg1:string):Promise<void>;
